# Generated by Django 5.0.6 on 2024-06-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiWine', '0003_user_isadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiWine.wine')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiWine.favorite'),
        ),
    ]
