# Generated by Django 5.0.6 on 2024-06-17 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiWine', '0004_favorite_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='apiWine.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite', to='apiWine.favorite'),
        ),
    ]
