# Generated by Django 5.0.6 on 2024-06-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiWine', '0005_favorite_user_alter_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='wine',
        ),
        migrations.AddField(
            model_name='favorite',
            name='wines',
            field=models.ManyToManyField(related_name='favorited_by', to='apiWine.wine'),
        ),
    ]
