# Generated by Django 5.0.6 on 2024-06-18 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiWine', '0008_remove_user_favorites_delete_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isAdmin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='wineType',
            new_name='wine_type',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiWine.user')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiWine.wine')),
            ],
        ),
    ]
